version: '3.8'
services:
  was:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    expose:
      - 8000
  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    depends_on:
      - was

volumes:
  static_volume:
  media_volume:
